name: Run
on:
  push: {}

jobs:
  run:
    name: Run the code
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Decrypt repo
        env:
          AES256_PASSPHRASE: ${{ secrets.AES256_PASSPHRASE }}
        run: echo "$AES256_PASSPHRASE" | gpg --passphrase-fd 0 -d source.tar.gz.gpg | tar -zxvf -
      - name: Run
        run: cargo run --release